
(async()=>{
 const B=window.academyBackend;if(!B)return;const state=await B.ready;if(!state?.user)return;
 const sb=B.client,user=state.user,page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
 const toast=document.querySelector('.toast,#toast');let timer;const say=m=>{if(!toast)return;toast.textContent=m;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),2600)};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const formObject=f=>Object.fromEntries(new FormData(f).entries());
 async function saveTask(key,title,done=true,extra={}){const {error}=await sb.from('hu_academy_tasks').upsert({user_id:user.id,client_key:key,title,stage:'OPEN',done,updated_at:new Date().toISOString(),...extra},{onConflict:'user_id,client_key'});if(error)throw error}
 async function saveSubmission(kind,key,title,content,metadata={}){const {error}=await sb.from('hu_academy_submissions').upsert({user_id:user.id,kind,client_key:key,title,content,metadata,status:'submitted',updated_at:new Date().toISOString()},{onConflict:'user_id,kind,client_key'});if(error)throw error}
 document.querySelectorAll('[data-check]').forEach(btn=>btn.addEventListener('click',async()=>{btn.disabled=true;try{await saveTask(btn.dataset.check,btn.closest('.card,.item')?.querySelector('h3,b')?.textContent||btn.dataset.check,true);btn.textContent='완료됨 ✓';btn.classList.add('ghost');say('완료 상태를 계정에 저장했습니다.')}catch(e){say('저장 중 오류가 발생했습니다.');console.error(e)}finally{btn.disabled=false}}));
 document.querySelectorAll('[data-event]').forEach(btn=>btn.addEventListener('click',async()=>{btn.disabled=true;try{const title=btn.closest('.card')?.querySelector('h2,h3')?.textContent||'아카데미 이벤트';await saveSubmission('event_registration',btn.dataset.event,title,'참석 신청',{event_key:btn.dataset.event});btn.textContent='신청 완료 ✓';say('이벤트 신청을 계정에 저장했습니다.')}catch(e){say('신청 저장 중 오류가 발생했습니다.');console.error(e)}finally{btn.disabled=false}}));
 document.querySelectorAll('[data-save]').forEach(btn=>btn.addEventListener('click',async()=>{const form=btn.closest('form');if(form&&!form.reportValidity())return;const d=form?formObject(form):{};btn.disabled=true;try{switch(btn.dataset.save){
  case'profile':await sb.from('hu_profiles').update({display_name:d.name||null,updated_at:new Date().toISOString()}).eq('user_id',user.id);{const{error}=await sb.from('hu_academy_user_profiles').upsert({user_id:user.id,region:d.region||null,target_timeline:d.timeline||null,budget_text:d.budget||null,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error}break;
  case'settings':{const{data:old}=await sb.from('hu_academy_user_profiles').select('settings').eq('user_id',user.id).maybeSingle();const{error}=await sb.from('hu_academy_user_profiles').upsert({user_id:user.id,settings:{...(old?.settings||{}),...d},updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error}break;
  case'mission_evidence':await saveTask('evidence-'+String(d.mission||'mission').replace(/\s+/g,'-'),d.mission||'실행 인증',true,{evidence_text:d.evidence||null,evidence_url:d.proof||null,metadata:{mission:d.mission||null}});break;
  case'mentor_question':await saveSubmission('mentor_question','latest-mentor-question',d.question||'멘토링 질문',d.tried||'',{stage:d.stage||null,question:d.question||null});break;
  case'community_post':await saveSubmission('community_post','post-'+Date.now(),d.title||'커뮤니티 글',d.content||'',{category:d.category||'질문'});await loadCommunity();break;
  case'profit_action':{const amount=Number(d.amount||0);await saveSubmission('profit_action','profit-'+Date.now(),d.type||'수익 행동',d.result||'',{amount,type:d.type||null});if(amount>0){const{error}=await sb.from('hu_academy_outcomes').insert({user_id:user.id,outcome_type:'first_revenue',status:'in_progress',source:'academy_user',metadata:{amount,type:d.type||null,result:d.result||null}});if(error)throw error}}break;
 }say(btn.dataset.message||'계정에 저장했습니다.')}catch(e){say('저장 중 오류가 발생했습니다.');console.error(e)}finally{btn.disabled=false}}));
 const ai=document.querySelector('[data-ai-form]');if(ai)ai.addEventListener('submit',async e=>{e.preventDefault();const q=String(new FormData(ai).get('question')||'');let a='먼저 현재 단계와 이번 주 실행 목표를 하나로 줄여보세요.';if(q.includes('매물'))a='매물은 지역·예산·허용업종·예상 매출 순으로 조건을 좁히고, 공실헬퍼에서 실제 후보를 비교하세요.';else if(q.includes('수익')||q.includes('매출'))a='월매출보다 고정비·변동비·공실률을 먼저 넣어 손익분기점을 계산한 뒤 판단하세요.';else if(q.includes('세팅'))a='오픈 필수품과 매출에 직접 영향을 주는 항목을 먼저 세팅하고 장식 요소는 뒤로 미루세요.';else if(q.includes('운영'))a='예약→체크인→청소→CS→리뷰 흐름을 체크리스트로 만들고 반복 업무부터 자동화하세요.';const out=document.querySelector('[data-ai-answer]');if(out)out.textContent=a;await saveSubmission('ai_question','ai-'+Date.now(),'AI 학습 질문',q,{answer:a}).catch(console.error)});
 async function loadTaskStates(){const{data}=await sb.from('hu_academy_tasks').select('client_key,done').eq('user_id',user.id);const done=new Set((data||[]).filter(x=>x.done).map(x=>x.client_key));document.querySelectorAll('[data-check]').forEach(btn=>{if(done.has(btn.dataset.check)){btn.textContent='완료됨 ✓';btn.classList.add('ghost')}})}
 async function loadProfile(){if(page!=='profile.html'&&page!=='settings.html')return;const[{data:hub},{data:ap}]=await Promise.all([sb.from('hu_profiles').select('display_name,helper_id,current_stage').eq('user_id',user.id).maybeSingle(),sb.from('hu_academy_user_profiles').select('*').eq('user_id',user.id).maybeSingle()]);const form=document.querySelector('.form');if(!form)return;if(page==='profile.html'){if(form.elements.name)form.elements.name.value=hub?.display_name||'';if(form.elements.region)form.elements.region.value=ap?.region||'';if(form.elements.timeline&&ap?.target_timeline)form.elements.timeline.value=ap.target_timeline;if(form.elements.budget)form.elements.budget.value=ap?.budget_text||''}else if(ap?.settings){for(const[k,v]of Object.entries(ap.settings))if(form.elements[k])form.elements[k].value=v}}
 async function enroll(c){const payment_status=Number(c.price)===0?'paid':'not_connected';const{error}=await sb.from('hu_academy_enrollments').insert({user_id:user.id,course_id:c.id,progress:0,status:'active',payment_status});if(error&&!String(error.message).includes('duplicate'))throw error;say(payment_status==='paid'?'무료 과정 수강이 활성화되었습니다.':'수강 신청 완료. 실제 결제 연결 후 강의가 활성화됩니다.');await loadCourses()}
 async function loadCourses(){const root=document.getElementById('dbCourseCatalog');if(!root)return;const[{data:courses,error:ce},{data:enrollments}]=await Promise.all([sb.from('hu_academy_courses').select('id,title,category,summary,price,lessons,status').eq('status','published').order('price'),sb.from('hu_academy_enrollments').select('course_id,progress,status,payment_status').eq('user_id',user.id)]);if(ce){root.innerHTML='<article class="card"><p>과정을 불러오지 못했습니다.</p></article>';return}const map=new Map((enrollments||[]).map(e=>[e.course_id,e]));root.innerHTML=(courses||[]).map(c=>{const e=map.get(c.id),paid=e?.payment_status==='paid';const button=e?`<a class="btn block ${paid?'':'secondary'}" href="./course.html?id=${encodeURIComponent(c.id)}">${paid?'수강 중 · 강의 보기':'결제 대기 · 과정 보기'}</a>`:`<button class="btn block ${c.price?'secondary':''}" data-enroll="${esc(c.id)}">${c.price?'수강 신청':'무료 수강 시작'}</button>`;return`<article class="card"><span class="tag ${c.price?'blue':''}">${esc(c.category)}</span><h2 style="margin-top:8px">${esc(c.title)}</h2><p>${esc(c.summary||'')}</p><div class="course-price">${Number(c.price).toLocaleString('ko-KR')}원</div><div class="meta"><span class="tag gray">${c.lessons}강</span><span class="tag gray">${e?esc(e.payment_status):'미신청'}</span></div>${button}</article>`}).join('');root.querySelectorAll('[data-enroll]').forEach(btn=>btn.addEventListener('click',async()=>{const c=(courses||[]).find(x=>x.id===btn.dataset.enroll);if(!c)return;btn.disabled=true;try{await enroll(c)}catch(e){say('수강 신청 중 오류가 발생했습니다.');console.error(e)}finally{btn.disabled=false}}))}
 async function loadCourseDetail(){if(page!=='course.html')return;const root=document.getElementById('courseDetail'),id=new URLSearchParams(location.search).get('id');if(!id){root.innerHTML='<div class="empty">과정을 찾을 수 없습니다.</div>';return}const[{data:course,error:ce},{data:enrollment},{data:lessons}]=await Promise.all([sb.from('hu_academy_courses').select('*').eq('id',id).maybeSingle(),sb.from('hu_academy_enrollments').select('*').eq('user_id',user.id).eq('course_id',id).maybeSingle(),sb.from('hu_academy_lessons').select('id,course_id,position,title,summary,content,is_preview,duration_min').eq('course_id',id).order('position')]);if(ce||!course){root.innerHTML='<div class="empty">과정을 찾을 수 없습니다.</div>';return}const paid=enrollment?.payment_status==='paid';root.innerHTML=`<section class="card"><span class="tag">${esc(course.category)}</span><h2 style="margin-top:8px">${esc(course.title)}</h2><p>${esc(course.summary||'')}</p><div class="meta"><span class="tag gray">${Number(course.price).toLocaleString('ko-KR')}원</span><span class="tag gray">${paid?'수강 활성화':'결제 전'}</span></div></section><section class="card" style="margin-top:12px"><h2>강의 목록</h2><div class="list" id="lessonList"></div></section>`;const list=root.querySelector('#lessonList');if(!(lessons||[]).length){list.innerHTML='<div class="empty">등록된 강의를 준비 중입니다.</div>';return}list.innerHTML=(lessons||[]).map(l=>`<div class="item ${(!paid&&!l.is_preview)?'locked':''}"><span class="num">${l.position}</span><div class="grow"><b>${esc(l.title)}</b><small>${l.duration_min}분 · ${l.is_preview?'미리보기':paid?'수강 가능':'결제 후 열림'}</small>${(paid||l.is_preview)&&l.content?`<div class="lesson-content">${esc(l.content)}</div>`:''}</div>${paid?`<button class="btn secondary" data-lesson-id="${esc(l.id)}" data-course-id="${esc(id)}">완료</button>`:''}</div>`).join('');const{data:progress}=await sb.from('hu_academy_lesson_progress').select('lesson_id,completed').eq('user_id',user.id).eq('course_id',id);const done=new Set((progress||[]).filter(x=>x.completed).map(x=>x.lesson_id));list.querySelectorAll('[data-lesson-id]').forEach(btn=>{if(done.has(btn.dataset.lessonId)){btn.textContent='완료됨 ✓';btn.classList.add('ghost')}btn.addEventListener('click',async()=>{btn.disabled=true;const{error}=await sb.from('hu_academy_lesson_progress').upsert({user_id:user.id,course_id:btn.dataset.courseId,lesson_id:btn.dataset.lessonId,completed:true,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'user_id,lesson_id'});if(error){say('진도 저장 중 오류가 발생했습니다.');console.error(error)}else{btn.textContent='완료됨 ✓';btn.classList.add('ghost');say('강의 진도를 저장했습니다.')}btn.disabled=false})})}
 async function loadCommunity(){const root=document.getElementById('communityList');if(!root)return;const{data,error}=await sb.from('hu_academy_submissions').select('id,title,content,metadata,created_at').eq('kind','community_post').order('created_at',{ascending:false}).limit(20);if(error){root.innerHTML='<div class="empty">게시글을 불러오지 못했습니다.</div>';return}root.innerHTML=(data||[]).length?(data||[]).map(p=>`<div class="item"><span class="num">${esc((p.metadata?.category||'글').slice(0,1))}</span><div class="grow"><b>${esc(p.title||'제목 없음')}</b><small>${esc(p.metadata?.category||'게시글')} · ${new Date(p.created_at).toLocaleDateString('ko-KR')}</small><p style="margin-top:5px">${esc(p.content||'')}</p></div></div>`).join(''):'<div class="empty">첫 글을 작성해보세요.</div>'}
 async function loadReport(){const[{data:tasks},{data:enroll},{data:progress},{data:ap}]=await Promise.all([sb.from('hu_academy_tasks').select('client_key,done').eq('user_id',user.id),sb.from('hu_academy_enrollments').select('course_id,payment_status,status').eq('user_id',user.id),sb.from('hu_academy_lesson_progress').select('lesson_id,completed').eq('user_id',user.id),sb.from('hu_academy_user_profiles').select('region,target_timeline,budget_text').eq('user_id',user.id).maybeSingle()]);const doneTasks=(tasks||[]).filter(x=>x.done).length,active=(enroll||[]).filter(x=>x.status==='active').length,doneLessons=(progress||[]).filter(x=>x.completed).length,coreDone=(tasks||[]).filter(x=>x.done&&['mission-1','mission-2','mission-3'].includes(x.client_key)).length,profileComplete=Boolean(ap?.region&&ap?.target_timeline&&ap?.budget_text),readiness=Math.min(100,coreDone*25+(profileComplete?25:0));if(page==='report.html'){const v=document.querySelectorAll('.g4 .stat strong');if(v[0])v[0].textContent=doneLessons+'강';if(v[1])v[1].textContent=doneTasks+'개';if(v[2])v[2].textContent=active+'개';if(v[3])v[3].textContent=readiness+'%'}if(page==='index.html'){const v=document.querySelectorAll('.stats-row strong');if(v[0])v[0].textContent=doneLessons+'강 완료';if(v[1])v[1].textContent=active+'개';if(v[2])v[2].textContent=doneTasks+'개';if(v[3])v[3].textContent=readiness+'%'}}
 await Promise.all([loadTaskStates(),loadProfile(),loadCourses(),loadCourseDetail(),loadCommunity(),loadReport()]);
})();
