(()=>{
let started=false;
const statusKo={draft:'초안',published:'공개',reviewing:'검토중',verified:'검증완료',needs_info:'보완요청',rejected:'반려',submitted:'접수',broker_assigned:'중개사 배정',consulting:'상담중',visit_scheduled:'방문예정',condition_review:'조건검토',negotiating:'계약협의',closed:'종료',active:'진행중',completed:'완료',paused:'일시정지',request:'요청접수',survey:'현장실측',quote:'견적',contract:'계약',order:'발주',install:'설치',inspection:'검수',complete:'완료',cancelled:'취소',onboarding:'온보딩',operating:'운영중',todo:'대기',in_progress:'진행중',done:'완료',blocked:'차단',requested:'요청접수',proposed:'제안중',accepted:'수락',confirmed:'예약확정',sent:'제안발송',declined:'거절',withdrawn:'철회',checked_in:'체크인',checked_out:'체크아웃',settled:'정산완료',pending:'대기'};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const hu=()=>window.HU;
const esc=v=>hu().esc(v), money=v=>hu().money(v);
function clean(){ $$('.huDataInjected').forEach(e=>e.remove()) }
function live(title,body,meta=''){const e=document.createElement('section');e.className='huLive huDataInjected';e.innerHTML=`<div class="huLiveHead"><h2>${esc(title)}</h2><span>${esc(meta)}</span></div>${body}`;return e}
function empty(t='아직 데이터가 없습니다.'){return `<div class="huEmpty">${esc(t)}</div>`}
function table(headers,rows){return `<div style="overflow:auto"><table class="table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function st(v){return `<span class="huStatus">${esc(statusKo[v]||v||'-')}</span>`}
function btn(label,action,id='',primary=false,extra=''){return `<button class="${primary?'primary':''}" data-live-action="${action}" ${id?`data-id="${id}"`:''} ${extra}>${esc(label)}</button>`}
async function q(name,run){try{const r=await run();if(r?.error)throw r.error;return r?.data}catch(e){hu().fail(e,`${name} 처리에 실패했습니다.`);return null}}
async function refreshSoon(){await hu().loadAccount().catch(()=>{});await hu().refresh();await render()}
function target(screen){return $(`#${screen} .main`)||$(`#${screen}`)||$('.main')}
function prepend(screen,node){const t=target(screen);if(t)t.prepend(node)}
function after(selector,node,root=document){const ref=$(selector,root);if(ref)ref.after(node);else (root.querySelector?.('.main')||root).prepend?.(node)}
async function render(){if(!window.HU?.sb)return;clean();const svc=hu().cfg.service;if(svc==='gongsil')return gongsil();if(svc==='academy')return academy();if(svc==='house')return house();if(svc==='host')return host();if(svc==='life')return life();if(svc==='next')return next();if(svc==='universe')return universe()}

async function universe(){
 const cards=$$('.card');const links={공실헬퍼:'gongsil.html',헬퍼아카데미:'academy.html',하우스헬퍼:'house.html',호스트헬퍼:'host.html',라이프헬퍼:'life.html',넥스트헬퍼:'next.html'};
 cards.forEach(c=>{const name=c.querySelector('.body b')?.textContent?.trim();if(links[name]){c.tabIndex=0;c.setAttribute('role','link');c.dataset.liveHref=links[name]}});
 if(!hu().user)return;
 const wrap=$('.wrap .life')?.parentElement||$('.wrap');if(!wrap)return;
 const body=`<div class="kv"><div><span>Helper ID</span><b>${esc(hu().profile?.helper_id||'-')}</b></div><div><span>현재 단계</span><b>${esc(hu().journey?.current_stage||'FIND')}</b></div><div><span>다음 서비스</span><b>${esc(hu().journey?.next_service||'완료')}</b></div><div><span>다음 행동</span><b>${esc(hu().journey?.next_action||'현재 여정을 이어가세요.')}</b></div></div><div class="huActionRow" style="margin-top:12px">${Object.entries(links).map(([n,h])=>`<button class="primary" data-live-href="${h}">${esc(n)}</button>`).join('')}</div>`;
 wrap.appendChild(live('나의 Helper 진행상태',body,'통합 Helper ID'));
}

async function gongsil(){
 const sb=hu().sb;
 const listings=await q('매물 조회',()=>sb.from('hu_gongsil_listings').select('*').order('created_at',{ascending:false}).limit(30));
 if(listings){const grid=$('#user .cards');if(grid)grid.innerHTML=listings.map(l=>`<article class="card" data-live-listing="${l.id}" style="cursor:pointer"><div class="cardImg"><span class="chip ${l.verification_status==='verified'?'':'warn'}">${esc(statusKo[l.verification_status]||l.verification_status)}</span></div><div class="cardBody"><h3>${esc(l.title)}</h3><p>${esc(l.property_type)} · 객실 ${l.rooms}개 · ${esc(l.region)}</p><div class="price">예상 월매출 ${Number(l.expected_revenue_min||0)/10000}~${Number(l.expected_revenue_max||0)/10000}만원</div><p>권리금 ${money(l.premium)} · ${esc(l.facts?.source||'근거 확인 필요')}</p></div></article>`).join('')}
 if(!hu().user)return;
 const ok=await q('카카오 검증 확인',()=>sb.rpc('hu_gongsil_kakao_ok'));
 const inquiries=await q('내 문의',()=>sb.from('hu_gongsil_inquiries').select('id,status,note,created_at,listing_id,hu_gongsil_listings(title,region)').eq('user_id',hu().user.id).order('created_at',{ascending:false}));
 const myRows=(inquiries||[]).map(i=>`<tr><td>${esc(i.hu_gongsil_listings?.title||'-')}</td><td>${st(i.status)}</td><td>${new Date(i.created_at).toLocaleDateString('ko-KR')}</td><td><div class="huActionRow">${['submitted','broker_assigned','consulting'].includes(i.status)?btn('현장방문 요청','gongsil-visit',i.id,true):''}</div></td></tr>`);
 const userPanel=live('실제 거래 진행 워크스페이스',`${ok?'<div class="notice">카카오 계정 검증 완료 · 매물 등록/문의 기능을 사용할 수 있습니다.</div>':'<div class="notice" style="background:#fff6d7;color:#735f00">공실헬퍼의 거래 기능은 카카오 인증이 필요합니다. <button class="huBtn" data-hu-kakao>카카오 인증</button></div>'}<div style="margin-top:14px">${table(['문의 매물','상태','접수일','다음 행동'],myRows)||empty()}</div><details style="margin-top:14px"><summary style="font-weight:800;cursor:pointer">내 숙박사업 매물 등록</summary><form class="huForm" data-live-form="gongsil-listing" style="margin-top:12px"><label>매물명<input name="title" required></label><label>지역<input name="region" required placeholder="서울 마포구"></label><label>숙박업 유형<input name="type" required placeholder="게스트하우스/호텔/레지던스"></label><label>객실 수<input name="rooms" type="number" min="1" value="4" required></label><label>예상 월매출 최소<input name="revmin" type="number" min="0"></label><label>예상 월매출 최대<input name="revmax" type="number" min="0"></label><label>권리금<input name="premium" type="number" min="0"></label><button>검증 요청으로 등록</button></form></details>`,'카카오 검증 게이트');
 after('#user .grid2',userPanel,$('#user'));
 if(hu().hasRole('broker')||hu().isOperator()){
   const all=await q('문의 관리',()=>sb.from('hu_gongsil_inquiries').select('id,user_id,status,note,created_at,listing_id,hu_gongsil_listings(title,region)').order('created_at',{ascending:false}).limit(50));
   const rows=(all||[]).map(i=>`<tr><td>${esc(i.hu_gongsil_listings?.title||'-')}</td><td>${esc(i.hu_gongsil_listings?.region||'-')}</td><td>${st(i.status)}</td><td><div class="huActionRow">${btn('상담중','gongsil-status',i.id,false,'data-status="consulting"')}${btn('방문예정','gongsil-status',i.id,false,'data-status="visit_scheduled"')}${btn('조건검토','gongsil-status',i.id,false,'data-status="condition_review"')}${btn('계약협의','gongsil-status',i.id,true,'data-status="negotiating"')}</div></td></tr>`);
   prepend(hu().isOperator()?'operator':'broker',live('실DB 문의·현장 진행 관리',table(['매물','지역','상태','처리'],rows),'실시간 DB'));
 }
 if(hu().isOperator()&&listings){const rows=listings.map(l=>`<tr><td>${esc(l.title)}</td><td>${esc(l.region)}</td><td>${st(l.verification_status)}</td><td><div class="huActionRow">${btn('승인','gongsil-verify',l.id,true,'data-status="verified"')}${btn('보완','gongsil-verify',l.id,false,'data-status="needs_info"')}${btn('반려','gongsil-verify',l.id,false,'data-status="rejected"')}</div></td></tr>`);prepend('operator',live('실DB 매물 검증 큐',table(['매물','지역','검증','결정'],rows),`${listings.length}건`))}
}
async function openGongsilDetail(id){const l=await q('매물 상세',()=>hu().sb.from('hu_gongsil_listings').select('*').eq('id',id).single());if(!l)return;const tags=(l.facts?.tags||[]).map(t=>`<span class="huStatus">${esc(t)}</span>`).join(' ');hu().openInfo(`<small>${esc(l.region)} · ${esc(l.property_type)}</small><h2>${esc(l.title)}</h2><div class="kv"><div><span>예상 월매출</span><b>${money(l.expected_revenue_min)} ~ ${money(l.expected_revenue_max)}</b></div><div><span>권리금</span><b>${money(l.premium)}</b></div><div><span>데이터 근거</span><b>${esc(l.facts?.source||'미확인')}</b></div><div><span>검증 상태</span><b>${esc(statusKo[l.verification_status]||l.verification_status)}</b></div></div><p><b>위험요소</b><br>${esc(l.facts?.risk||'추가 검토 필요')}</p><div class="huActionRow">${tags}</div><div class="huActionRow" style="margin-top:16px">${btn('상담 문의','gongsil-inquire',l.id,true)}${btn('저장','save-item',l.id,false,'data-service="gongsil" data-label="'+esc(l.title)+'"')}</div>`) }

async function academy(){
 const sb=hu().sb;const courses=await q('교육과정',()=>sb.from('hu_academy_courses').select('*').eq('status','published').order('price'));
 for(const root of [$('#student .cards'),$('#courses .cards')])if(root&&courses)root.innerHTML=courses.map(c=>`<article class="card"><div class="cardImg"><span class="chip">${esc(c.category)}</span></div><div class="cardBody"><h3>${esc(c.title)}</h3><p>${esc(c.summary||'')}</p><p>총 ${c.lessons}강 · 실행형 과정</p><div class="price">${c.price?money(c.price):'무료'}</div>${hu().user?`<button class="btn" style="margin-top:10px;width:100%" data-live-action="academy-enroll" data-id="${c.id}">수강 시작/계속</button>`:'<button class="btn" style="margin-top:10px;width:100%" data-hu-login>로그인 후 수강</button>'}</div></article>`).join('');
 if(!hu().user)return;
 const enroll=await q('학습현황',()=>sb.from('hu_academy_enrollments').select('id,progress,status,course_id,hu_academy_courses(title,category)').eq('user_id',hu().user.id).order('updated_at',{ascending:false}));
 const tasks=await q('실행과제',()=>sb.from('hu_academy_tasks').select('*').eq('user_id',hu().user.id).order('created_at',{ascending:false}));
 const er=(enroll||[]).map(e=>`<tr><td>${esc(e.hu_academy_courses?.title||'-')}</td><td>${e.progress}%</td><td>${st(e.status)}</td><td><div class="huActionRow">${e.progress<100?btn('+25% 학습완료','academy-progress',e.id,true,`data-progress="${Math.min(100,e.progress+25)}"`):''}</div></td></tr>`);
 const tr=(tasks||[]).map(t=>`<div class="huRoleReq"><div><b>${t.done?'✓ ':''}${esc(t.title)}</b><p>${esc(t.stage)} · ${t.due_date||'기한 없음'}</p></div><div class="huActionRow">${btn(t.done?'미완료로':'완료','academy-task-toggle',t.id,!t.done,`data-done="${!t.done}"`)}</div></div>`).join('');
 prepend('student',live('내 실제 OPEN 프로젝트',`${table(['과정','학습진도','상태','학습'],er)}<div style="margin-top:14px"><form class="huForm" data-live-form="academy-task"><label>다음 실행 과제<input name="title" required placeholder="예: 후보 입지 3곳 비교하기"></label><button>실행 과제 추가</button></form></div><div style="margin-top:14px">${tr||empty('실행 과제를 추가하면 숙소 오픈 진행을 관리할 수 있습니다.')}</div>`,'학습 → 실행 → OPEN'));
}

async function house(){
 if(!hu().user)return;const sb=hu().sb;const projects=await q('세팅 프로젝트',()=>sb.from('hu_house_projects').select('*').order('created_at',{ascending:false}).limit(50));
 const mine=(projects||[]).filter(p=>p.owner_id===hu().user.id||hu().isOperator());const rows=mine.map(p=>`<tr><td>${esc(p.address)}</td><td>${esc(p.package_name||'-')}</td><td>${st(p.status)}</td><td>${p.quote_total?money(p.quote_total):'산정중'}</td><td><div class="huActionRow">${btn('상세/체크','house-detail',p.id,true)}</div></td></tr>`);
 prepend('quote',live('내 객실 SETUP 프로젝트',table(['공간','패키지','진행','견적','관리'],rows),`${mine.length}건`));
 if(hu().isOperator()){const all=projects||[];const r=all.map(p=>`<tr><td>${esc(p.address)}</td><td>${st(p.status)}</td><td>${p.target_date||'-'}</td><td><div class="huActionRow">${nextHouseStatus(p.status)?btn('다음 단계','house-next',p.id,true,`data-status="${nextHouseStatus(p.status)}"`):''}</div></td></tr>`);prepend('operator',live('전체 설치 프로젝트 파이프라인',table(['공간','상태','오픈목표','진행'],r),`${all.length}건`))}
}
function nextHouseStatus(s){return ({request:'survey',survey:'quote',quote:'contract',contract:'order',order:'install',install:'inspection',inspection:'complete'})[s]||''}
async function houseDetail(id){const sb=hu().sb;const p=await q('프로젝트 상세',()=>sb.from('hu_house_projects').select('*').eq('id',id).single());if(!p)return;if(['install','inspection','complete'].includes(p.status)){let checks=await q('설치 체크',()=>sb.from('hu_house_install_checks').select('*').eq('project_id',id).order('label'));if(checks&&!checks.length&&p.owner_id===hu().user.id){await sb.from('hu_house_install_checks').insert(['가구 반입 및 배치','침구 세팅','가전 설치','욕실용품 세팅','최종 점검 및 고객 확인'].map(label=>({project_id:id,label})));checks=await q('설치 체크',()=>sb.from('hu_house_install_checks').select('*').eq('project_id',id).order('label'))}hu().openInfo(`<small>PROJECT</small><h2>${esc(p.address)}</h2><p>${esc(p.package_name||'맞춤 세팅')} · ${statusKo[p.status]||p.status}</p>${(checks||[]).map(c=>`<div class="huRoleReq"><b>${c.done?'✓ ':''}${esc(c.label)}</b><div class="huActionRow">${btn(c.done?'완료':'체크','house-check',c.id,!c.done,`data-done="${!c.done}"`)}</div></div>`).join('')||empty()}`)}else hu().openInfo(`<h2>${esc(p.address)}</h2><p>현재 단계: ${esc(statusKo[p.status]||p.status)}</p><div class="kv"><div><span>공간 유형</span><b>${esc(p.space_type)}</b></div><div><span>오픈 목표일</span><b>${esc(p.target_date||'-')}</b></div><div><span>패키지</span><b>${esc(p.package_name||'-')}</b></div><div><span>견적</span><b>${p.quote_total?money(p.quote_total):'산정중'}</b></div></div>`)}

async function host(){
 if(!hu().user)return;const sb=hu().sb;if(!(hu().hasRole('host')||hu().isOperator()))return;
 const props=await q('운영숙소',()=>sb.from('hu_host_properties').select('*').order('created_at',{ascending:false}).limit(100));
 const mine=(props||[]).filter(p=>p.owner_id===hu().user.id||hu().isOperator());
 const rows=mine.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.region||'-')}</td><td>${st(p.status)}</td><td>${Number(p.occupancy||0).toFixed(0)}%</td><td>${money(p.expected_settlement)}</td><td>${btn('운영업무','host-property',p.id,true)}</td></tr>`);
 const form=`<details><summary style="font-weight:800;cursor:pointer">+ 위탁/운영 숙소 온보딩</summary><form class="huForm" data-live-form="host-property" style="margin-top:12px"><label>숙소명<input name="name" required></label><label>지역<input name="region" required></label><label>객실 수<input name="rooms" type="number" min="1" value="1"></label><button>온보딩 시작</button></form></details>`;
 prepend('host',live('실제 Host Workspace',`${table(['숙소','지역','운영상태','점유율','예상정산','업무'],rows)}<div style="margin-top:14px">${form}</div>`,'OPERATE SaaS'));
 if(hu().isOperator()){const all=props||[];const r=all.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.region||'-')}</td><td>${st(p.status)}</td><td><div class="huActionRow">${['onboarding','inspection','paused'].includes(p.status)?btn('운영시작','host-status',p.id,true,'data-status="operating"'):btn('점검중','host-status',p.id,false,'data-status="inspection"')}</div></td></tr>`);prepend('ops',live('전체 숙소 운영 Control Tower',table(['숙소','지역','상태','운영처리'],r),`${all.length}개`))}
}
async function hostProperty(id){const sb=hu().sb;const p=await q('숙소',()=>sb.from('hu_host_properties').select('*').eq('id',id).single());if(!p)return;const tasks=await q('운영업무',()=>sb.from('hu_host_tasks').select('*').eq('property_id',id).order('scheduled_at',{ascending:true}));hu().openInfo(`<small>OPERATE</small><h2>${esc(p.name)}</h2><div class="kv"><div><span>점유율</span><b>${Number(p.occupancy||0).toFixed(0)}%</b></div><div><span>ADR</span><b>${money(p.adr)}</b></div><div><span>예상 정산</span><b>${money(p.expected_settlement)}</b></div><div><span>상태</span><b>${esc(statusKo[p.status]||p.status)}</b></div></div><form class="huForm" data-live-form="host-task" data-property="${p.id}" style="margin-top:16px"><label>업무 유형<select name="type"><option>cleaning</option><option>guest</option><option>pricing</option><option>review</option><option>issue</option></select></label><label>업무 제목<input name="title" required placeholder="예: 1201호 체크인 전 청소"></label><button>업무 추가</button></form><div style="margin-top:14px">${(tasks||[]).map(t=>`<div class="huRoleReq"><div><b>${esc(t.title)}</b><p>${esc(t.task_type)} · ${statusKo[t.status]||t.status}</p></div><div class="huActionRow">${t.status!=='done'?btn('완료','host-task-done',t.id,true):st('done')}</div></div>`).join('')||empty()}</div>`)}

async function life(){
 const sb=hu().sb;const spaces=await q('숙소',()=>sb.from('hu_life_spaces').select('*').eq('status','published').order('nightly_price').limit(30));
 if(spaces){const grid=$('#guest .cards:nth-of-type(2)')||$('#guest .toolbar')?.nextElementSibling;if(grid?.classList.contains('cards'))grid.innerHTML=spaces.map(s=>`<article class="card"><div class="cardImg"><span class="chip">검증 숙소</span></div><div class="cardBody"><h3>${esc(s.title)}</h3><p>${esc(s.region)} · 최대 ${s.capacity}명</p><div class="price">1박 ${money(s.nightly_price)}~</div><div class="huActionRow" style="margin-top:10px">${btn('상세','life-space',s.id,true)}${hu().user?btn('저장','save-item',s.id,false,'data-service="life" data-label="'+esc(s.title)+'"'):''}</div></div></article>`).join('')}
 if(!hu().user)return;
 const reqs=await q('숙박요청',()=>sb.from('hu_life_requests').select('*').order('created_at',{ascending:false}).limit(100));const mine=(reqs||[]).filter(r=>r.user_id===hu().user.id);
 const ownRows=[];for(const r of mine){const proposals=await q('제안',()=>sb.from('hu_life_proposals').select('id,total_price,status,message,space_id,hu_life_spaces(title)').eq('request_id',r.id));ownRows.push(`<tr><td>${esc(r.region)}<br><small>${r.start_date}~${r.end_date}</small></td><td>${r.guest_count}명</td><td>${st(r.status)}</td><td>${(proposals||[]).map(p=>`<div style="margin-bottom:5px">${esc(p.hu_life_spaces?.title||'숙소 제안')} · ${money(p.total_price)} ${p.status==='sent'?btn('수락','life-accept',p.id,true):st(p.status)}</div>`).join('')||'제안 대기'}</td></tr>`)}
 prepend('guest',live('내 숙박 요청 · 제안 · 예약',`${table(['요청','인원','상태','호스트 제안'],ownRows)}<details style="margin-top:14px"><summary style="font-weight:800;cursor:pointer">+ 새로운 숙박 요청</summary><form class="huForm" data-live-form="life-request" style="margin-top:12px"><label>희망 지역<input name="region" required value="서울"></label><label>체크인<input name="start" type="date" required></label><label>체크아웃<input name="end" type="date" required></label><label>인원<input name="guests" type="number" min="1" value="2" required></label><label>목적<input name="purpose" placeholder="행사 참가/가족 여행/교육 등"></label><button>숙박 요청하기</button></form></details>`,'FILL'));
 const partner=hu().hasRole('host')||hu().hasRole('supplier')||hu().isOperator();if(partner){const mySpaces=await q('내 숙소',()=>sb.from('hu_life_spaces').select('*').eq('owner_id',hu().user.id).order('created_at',{ascending:false}));const requestRows=(reqs||[]).filter(r=>['requested','proposed'].includes(r.status)).map(r=>`<tr><td>${esc(r.region)}</td><td>${r.start_date}~${r.end_date}</td><td>${r.guest_count}명</td><td>${esc(r.purpose||'-')}</td><td><div class="huActionRow">${btn('제안 작성','life-propose',r.id,true)}</div></td></tr>`);prepend('host',live('공급자/호스트 실시간 요청 매칭',`${table(['희망지역','기간','인원','목적','제안'],requestRows)}<details style="margin-top:14px"><summary style="font-weight:800;cursor:pointer">+ 숙소/서비스 공급 등록</summary><form class="huForm" data-live-form="life-space" style="margin-top:12px"><label>숙소명<input name="title" required></label><label>지역<input name="region" required></label><label>1박 가격<input name="price" type="number" min="1" required></label><label>최대인원<input name="capacity" type="number" min="1" value="2"></label><button>검토용 숙소 등록</button></form></details><p style="margin-top:12px;color:#6b7880;font-size:10px">내 등록 숙소 ${(mySpaces||[]).length}개 · 운영자 승인 후 공개됩니다.</p>`,'REQUEST → PROPOSAL → RESERVATION'))}
 if(hu().isOperator()){const reservations=await q('예약',()=>sb.from('hu_life_reservations').select('*').order('created_at',{ascending:false}).limit(50));const rows=(reqs||[]).map(r=>`<tr><td>${esc(r.region)}</td><td>${r.start_date}~${r.end_date}</td><td>${r.guest_count}</td><td>${st(r.status)}</td></tr>`);prepend('operator',live('전체 숙박수요·예약 Control Tower',`${table(['지역','기간','인원','상태'],rows)}<p style="margin-top:12px;font-size:10px;color:#6b7880">확정/진행 예약 ${(reservations||[]).length}건</p>`,'운영자 CRM'))}
}
async function openLifeSpace(id){const s=await q('숙소상세',()=>hu().sb.from('hu_life_spaces').select('*').eq('id',id).single());if(!s)return;hu().openInfo(`<small>검증 숙소</small><h2>${esc(s.title)}</h2><div class="kv"><div><span>지역</span><b>${esc(s.region)}</b></div><div><span>1박</span><b>${money(s.nightly_price)}</b></div><div><span>최대 인원</span><b>${s.capacity}명</b></div><div><span>상태</span><b>${esc(statusKo[s.status]||s.status)}</b></div></div><p>${(s.details?.tags||[]).map(t=>`<span class="huStatus">${esc(t)}</span>`).join(' ')}</p>${hu().user?'<div class="notice">맞춤 숙박 요청을 등록하면 호스트의 실제 제안을 받을 수 있습니다.</div>':'<button class="huBtn primary" data-hu-login>로그인 후 예약 요청</button>'}`)}

async function next(){
 if(!hu().user)return;const sb=hu().sb;const [profiles,needs,offers,matches]=await Promise.all([q('프로필',()=>sb.from('hu_next_profiles').select('*')),q('NEED',()=>sb.from('hu_next_needs').select('*').eq('status','active')),q('OFFER',()=>sb.from('hu_next_offers').select('*').eq('status','active')),q('매칭',()=>sb.from('hu_next_matches').select('*').or(`sender_id.eq.${hu().user.id},recipient_id.eq.${hu().user.id}`).order('created_at',{ascending:false}))]);
 const me=(profiles||[]).find(p=>p.user_id===hu().user.id);const myNeeds=(needs||[]).filter(n=>n.user_id===hu().user.id);const myOffers=(offers||[]).filter(o=>o.user_id===hu().user.id);
 const profileForm=`<form class="huForm" data-live-form="next-profile"><label>한 줄 소개<input name="headline" required value="${esc(me?.headline||'')}"></label><label>지역<input name="region" value="${esc(me?.region||'')}"></label><label>사업 소개<textarea name="bio">${esc(me?.bio||'')}</textarea></label><button>사업 프로필 저장</button></form>`;
 const wantOffer=`<div class="grid2" style="margin-top:14px"><div><h3>WANT</h3>${myNeeds.map(n=>`<div class="notice">${esc(n.title)}</div>`).join('')||empty()}<form class="huForm" data-live-form="next-need" style="margin-top:10px"><label>필요한 것<input name="title" required></label><button>WANT 등록</button></form></div><div><h3>OFFER</h3>${myOffers.map(o=>`<div class="notice">${esc(o.title)}</div>`).join('')||empty()}<form class="huForm" data-live-form="next-offer" style="margin-top:10px"><label>제공할 수 있는 것<input name="title" required></label><button>OFFER 등록</button></form></div></div>`;
 prepend('matches',live('내 사업 프로필 · WANT / OFFER',profileForm+wantOffer,'첫 매칭 준비'));
 const others=(profiles||[]).filter(p=>p.user_id!==hu().user.id);const cards=others.map(p=>{const score=Math.min(95,60+((myNeeds.length+myOffers.length)*7));return `<article class="card"><div class="cardBody"><span class="chip">매칭 ${score}%</span><h3>${esc(p.headline||'비즈니스 파트너')}</h3><p>${esc(p.region||'지역 미설정')}</p><p>${esc(p.bio||'사업 프로필을 확인해보세요.')}</p><button class="btn" style="width:100%" data-live-action="next-match" data-id="${p.user_id}" data-score="${score}">매칭 요청</button></div></article>`}).join('');const home=$('#home .cards');if(home&&cards)home.innerHTML=cards;
 const incoming=(matches||[]).filter(m=>m.recipient_id===hu().user.id);const outgoing=(matches||[]).filter(m=>m.sender_id===hu().user.id);const rows=[...incoming,...outgoing].map(m=>`<tr><td>${m.sender_id===hu().user.id?'보낸 요청':'받은 요청'}</td><td>${m.score||'-'}%</td><td>${st(m.status)}</td><td><div class="huActionRow">${m.recipient_id===hu().user.id&&m.status==='pending'?btn('수락','next-respond',m.id,true,'data-decision="accepted"')+btn('거절','next-respond',m.id,false,'data-decision="declined"'):''}</div></td></tr>`);prepend('matches',live('내 비즈니스 매칭',table(['구분','적합도','상태','응답'],rows),`총 ${(matches||[]).length}건`));
 if(hu().isOperator()){const all=await q('전체매칭',()=>sb.from('hu_next_matches').select('*').order('created_at',{ascending:false}).limit(100));prepend('operator',live('매칭 품질·거래 진행 현황',table(['요청자','상대','적합도','상태'],(all||[]).map(m=>`<tr><td>${m.sender_id.slice(0,8)}</td><td>${m.recipient_id.slice(0,8)}</td><td>${m.score||'-'}%</td><td>${st(m.status)}</td></tr>`)),`${(all||[]).length}건`))}
}

async function saveItem(id,service,label){if(!await hu().requireAuth())return;const {error}=await hu().sb.from('hu_saved_items').upsert({user_id:hu().user.id,service,entity_id:id,label},{onConflict:'user_id,service,entity_id'});if(error)return hu().fail(error);hu().toast('저장했습니다.');hu().logEvent('save_item',{service,id})}

document.addEventListener('click',async e=>{
 const listing=e.target.closest('[data-live-listing]');if(listing)return openGongsilDetail(listing.dataset.liveListing);
 const href=e.target.closest('[data-live-href]');if(href){location.href=href.dataset.liveHref;return}
 const a=e.target.closest('[data-live-action]');if(!a)return;const action=a.dataset.liveAction,id=a.dataset.id;
 if(action==='save-item')return saveItem(id,a.dataset.service,a.dataset.label);
 if(action==='gongsil-inquire'){if(!await hu().requireAuth())return;const ok=await q('카카오 검증',()=>hu().sb.rpc('hu_gongsil_kakao_ok'));if(!ok)return hu().openInfo('<h2>카카오 인증이 필요합니다.</h2><p>공실헬퍼는 허위매물·사기 방지를 위해 거래 문의 전에 카카오 계정 인증을 별도로 확인합니다.</p><button class="huBtn primary" data-hu-kakao>카카오로 인증하기</button>');const {error}=await hu().sb.from('hu_gongsil_inquiries').insert({listing_id:id,user_id:hu().user.id,note:'웹 상세에서 상담 문의'});if(error)return hu().fail(error);hu().toast('상담 문의를 접수했습니다.');hu().logEvent('gongsil_inquiry',{listing_id:id});closeInfo();return refreshSoon()}
 if(action==='gongsil-status'){const {error}=await hu().sb.from('hu_gongsil_inquiries').update({status:a.dataset.status,updated_at:new Date().toISOString()}).eq('id',id);if(error)return hu().fail(error);hu().toast('진행 상태를 변경했습니다.');return refreshSoon()}
 if(action==='gongsil-verify'){const {error}=await hu().sb.from('hu_gongsil_listings').update({verification_status:a.dataset.status,updated_at:new Date().toISOString()}).eq('id',id);if(error)return hu().fail(error);hu().toast('검증 상태를 반영했습니다.');return refreshSoon()}
 if(action==='gongsil-visit')return hu().openInfo(`<h2>현장 방문 신청</h2><form class="huForm" data-live-form="gongsil-visit" data-inquiry="${id}"><label>희망 일시<input name="when" type="datetime-local" required></label><button>방문 요청</button></form>`);
 if(action==='academy-enroll'){if(!await hu().requireAuth())return;const {error}=await hu().sb.from('hu_academy_enrollments').upsert({user_id:hu().user.id,course_id:id,status:'active'},{onConflict:'user_id,course_id'});if(error)return hu().fail(error);hu().toast('학습을 시작합니다.');hu().setJourney('OPEN','academy','강의와 실행과제를 완료해 숙소 오픈 준비를 진행하세요.');return refreshSoon()}
 if(action==='academy-progress'){const p=Number(a.dataset.progress);const {error}=await hu().sb.from('hu_academy_enrollments').update({progress:p,status:p>=100?'completed':'active',updated_at:new Date().toISOString()}).eq('id',id);if(error)return hu().fail(error);hu().toast('학습 진도를 저장했습니다.');if(p>=100)await hu().setJourney('OPEN','house','학습 내용을 실제 객실 세팅 프로젝트로 연결해보세요.');return refreshSoon()}
 if(action==='academy-task-toggle'){const {error}=await hu().sb.from('hu_academy_tasks').update({done:a.dataset.done==='true',updated_at:new Date().toISOString()}).eq('id',id);if(error)return hu().fail(error);return refreshSoon()}
 if(action==='house-detail')return houseDetail(id);
 if(action==='house-next'){const s=a.dataset.status,{error}=await hu().sb.from('hu_house_projects').update({status:s,updated_at:new Date().toISOString()}).eq('id',id);if(error)return hu().fail(error);hu().toast('프로젝트 단계를 진행했습니다.');if(s==='complete')await hu().setJourney('SETUP','host','객실 세팅이 완료되었습니다. 운영을 시작하세요.');return refreshSoon()}
 if(action==='house-check'){const {error}=await hu().sb.from('hu_house_install_checks').update({done:a.dataset.done==='true',updated_at:new Date().toISOString()}).eq('id',id);if(error)return hu().fail(error);hu().toast('설치 체크를 저장했습니다.');return houseDetail((await hu().sb.from('hu_house_install_checks').select('project_id').eq('id',id).single()).data?.project_id)}
 if(action==='host-property')return hostProperty(id);
 if(action==='host-status'){const {error}=await hu().sb.from('hu_host_properties').update({status:a.dataset.status,updated_at:new Date().toISOString()}).eq('id',id);if(error)return hu().fail(error);hu().toast('숙소 운영 상태를 변경했습니다.');return refreshSoon()}
 if(action==='host-task-done'){const {error}=await hu().sb.from('hu_host_tasks').update({status:'done',updated_at:new Date().toISOString()}).eq('id',id);if(error)return hu().fail(error);hu().toast('업무를 완료했습니다.');return refreshSoon()}
 if(action==='life-space')return openLifeSpace(id);
 if(action==='life-propose'){const spaces=await q('내 숙소',()=>hu().sb.from('hu_life_spaces').select('id,title,nightly_price').eq('owner_id',hu().user.id));if(!spaces?.length)return hu().openInfo('<h2>먼저 숙소를 등록해주세요.</h2><p>운영자 검토용 숙소를 등록한 뒤 숙박 요청에 제안할 수 있습니다.</p>');hu().openInfo(`<h2>숙소 제안 보내기</h2><form class="huForm" data-live-form="life-proposal" data-request="${id}"><label>숙소<select name="space">${spaces.map(s=>`<option value="${s.id}">${esc(s.title)}</option>`).join('')}</select></label><label>총 제안금액<input name="price" type="number" min="1" required></label><label>메시지<textarea name="message" maxlength="800"></textarea></label><button>제안 보내기</button></form>`);return}
 if(action==='life-accept'){const {data,error}=await hu().sb.rpc('hu_accept_life_proposal',{p_proposal_id:id});if(error)return hu().fail(error);hu().toast('예약이 확정되었습니다.');hu().logEvent('life_reservation_confirmed',{reservation_id:data});return refreshSoon()}
 if(action==='next-match'){const {error}=await hu().sb.from('hu_next_matches').insert({sender_id:hu().user.id,recipient_id:id,score:Number(a.dataset.score||80),message:'헬퍼유니버스 비즈니스 매칭 요청'});if(error)return hu().fail(error);hu().toast('매칭 요청을 보냈습니다.');hu().logEvent('next_match_request',{recipient_id:id});return refreshSoon()}
 if(action==='next-respond'){const {error}=await hu().sb.rpc('hu_respond_next_match',{p_match_id:id,p_decision:a.dataset.decision});if(error)return hu().fail(error);hu().toast(a.dataset.decision==='accepted'?'첫 비즈니스 매칭이 성사되었습니다.':'매칭 요청을 거절했습니다.');return refreshSoon()}
});
function closeInfo(){document.querySelectorAll('.huModalBack.open').forEach(x=>x.classList.remove('open'))}
document.addEventListener('submit',async e=>{
 const f=e.target.closest('[data-live-form]');if(!f)return;e.preventDefault();if(!await hu().requireAuth())return;const fd=new FormData(f),type=f.dataset.liveForm,sb=hu().sb;
 if(type==='gongsil-listing'){const ok=await q('카카오 검증',()=>sb.rpc('hu_gongsil_kakao_ok'));if(!ok)return hu().toast('카카오 인증 후 등록할 수 있습니다.');const {error}=await sb.from('hu_gongsil_listings').insert({owner_id:hu().user.id,title:String(fd.get('title')),region:String(fd.get('region')),property_type:String(fd.get('type')),rooms:Number(fd.get('rooms')),expected_revenue_min:Number(fd.get('revmin')||0),expected_revenue_max:Number(fd.get('revmax')||0),premium:Number(fd.get('premium')||0),verification_status:'reviewing',status:'draft',facts:{source:'호스트 제공자료',risk:'운영자 검증 전'}});if(error)return hu().fail(error);hu().toast('매물 검증 요청을 등록했습니다.');return refreshSoon()}
 if(type==='gongsil-visit'){const {error}=await sb.from('hu_gongsil_visits').insert({inquiry_id:f.dataset.inquiry,user_id:hu().user.id,scheduled_at:new Date(String(fd.get('when'))).toISOString()});if(error)return hu().fail(error);await sb.from('hu_gongsil_inquiries').update({status:'visit_scheduled',updated_at:new Date().toISOString()}).eq('id',f.dataset.inquiry);closeInfo();hu().toast('현장 방문을 요청했습니다.');return refreshSoon()}
 if(type==='academy-task'){const {error}=await sb.from('hu_academy_tasks').insert({user_id:hu().user.id,title:String(fd.get('title')),stage:'OPEN'});if(error)return hu().fail(error);f.reset();return refreshSoon()}
 if(type==='host-property'){const {error}=await sb.from('hu_host_properties').insert({owner_id:hu().user.id,name:String(fd.get('name')),region:String(fd.get('region')),rooms:Number(fd.get('rooms')||1),status:'onboarding'});if(error)return hu().fail(error);hu().toast('숙소 온보딩을 시작했습니다.');await hu().setJourney('OPERATE','host','숙소 온보딩을 완료하고 실제 운영을 시작하세요.');return refreshSoon()}
 if(type==='host-task'){const {error}=await sb.from('hu_host_tasks').insert({property_id:f.dataset.property,owner_id:hu().user.id,task_type:String(fd.get('type')),title:String(fd.get('title')),status:'todo'});if(error)return hu().fail(error);closeInfo();hu().toast('운영 업무를 추가했습니다.');return refreshSoon()}
 if(type==='life-request'){const start=String(fd.get('start')),end=String(fd.get('end'));if(!start||!end||new Date(end)<=new Date(start))return hu().toast('체크아웃은 체크인 이후여야 합니다.');const {error}=await sb.from('hu_life_requests').insert({user_id:hu().user.id,region:String(fd.get('region')),start_date:start,end_date:end,guest_count:Number(fd.get('guests')),purpose:String(fd.get('purpose')||''),status:'requested'});if(error)return hu().fail(error);hu().toast('숙박 요청을 등록했습니다.');await hu().setJourney('FILL','life','호스트의 맞춤 숙소 제안을 확인하세요.');return refreshSoon()}
 if(type==='life-space'){const {error}=await sb.from('hu_life_spaces').insert({owner_id:hu().user.id,title:String(fd.get('title')),region:String(fd.get('region')),nightly_price:Number(fd.get('price')),capacity:Number(fd.get('capacity')||2),status:'reviewing',details:{source:'공급자 등록'}});if(error)return hu().fail(error);hu().toast('숙소를 검토 요청으로 등록했습니다.');return refreshSoon()}
 if(type==='life-proposal'){const {error}=await sb.from('hu_life_proposals').insert({request_id:f.dataset.request,host_id:hu().user.id,space_id:String(fd.get('space')),total_price:Number(fd.get('price')),message:String(fd.get('message')||''),status:'sent'});if(error)return hu().fail(error);await sb.from('hu_life_requests').update({status:'proposed',updated_at:new Date().toISOString()}).eq('id',f.dataset.request);closeInfo();hu().toast('맞춤 제안을 보냈습니다.');return refreshSoon()}
 if(type==='next-profile'){const {error}=await sb.from('hu_next_profiles').upsert({user_id:hu().user.id,headline:String(fd.get('headline')),region:String(fd.get('region')||''),bio:String(fd.get('bio')||''),updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)return hu().fail(error);hu().toast('사업 프로필을 저장했습니다.');return refreshSoon()}
 if(type==='next-need'){const {error}=await sb.from('hu_next_needs').insert({user_id:hu().user.id,title:String(fd.get('title')),status:'active'});if(error)return hu().fail(error);f.reset();return refreshSoon()}
 if(type==='next-offer'){const {error}=await sb.from('hu_next_offers').insert({user_id:hu().user.id,title:String(fd.get('title')),status:'active'});if(error)return hu().fail(error);f.reset();return refreshSoon()}
});
document.addEventListener('submit',async e=>{if(e.target.closest('[data-live-form],[data-hu-auth-form],[data-hu-role-form]'))return;const form=e.target;if(hu().cfg.service==='house'&&form.closest('#quote')&&form.classList.contains('form')){e.preventDefault();if(!await hu().requireAuth())return;const selects=form.querySelectorAll('select'),inputs=form.querySelectorAll('input'),ta=form.querySelector('textarea');const payload={owner_id:hu().user.id,space_type:selects[0]?.value||'숙박업',address:inputs[0]?.value||'',target_date:inputs[1]?.value||null,package_name:selects[1]?.value||'맞춤 세팅',status:'request',details:{note:ta?.value||''}};if(!payload.address)return hu().toast('공간 주소를 입력해주세요.');const {error}=await hu().sb.from('hu_house_projects').insert(payload);if(error)return hu().fail(error);hu().toast('견적 요청을 접수했습니다.');await hu().setJourney('SETUP','house','현장 실측과 맞춤 견적을 확인하세요.');return refreshSoon()}});
document.addEventListener('keydown',e=>{const c=e.target.closest?.('[data-live-href]');if(c&&(e.key==='Enter'||e.key===' ')){e.preventDefault();location.href=c.dataset.liveHref}});
document.addEventListener('hu:ready',()=>{started=true;render()});document.addEventListener('hu:auth',()=>{if(started)render()});document.addEventListener('hu:screen',()=>{if(started)setTimeout(render,0)});
if(window.HU?.sb){started=true;render()}
})();