(()=>{
const wait=()=>new Promise(resolve=>{if(window.HU?.sb)return resolve();document.addEventListener('hu:ready',()=>resolve(),{once:true})});
const esc=v=>window.HU?.esc(v)||String(v||'');
const recommend=(text)=>{const q=(text||'').toLowerCase();if(/매물|공실|건물|임대|권리금|입지/.test(q))return{stage:'FIND',service:'gongsil',page:'gongsil.html',label:'공실헬퍼',action:'검증된 숙박사업 매물과 사업성을 확인하세요.'};if(/배우|강의|교육|초보|오픈 준비/.test(q))return{stage:'OPEN',service:'academy',page:'academy.html',label:'헬퍼아카데미',action:'무료 오픈진단과 실행형 교육과정을 시작하세요.'};if(/가구|침대|침구|세팅|인테리어|비품/.test(q))return{stage:'SETUP',service:'house',page:'house.html',label:'하우스헬퍼',action:'객실 세팅 견적과 설치 프로젝트를 시작하세요.'};if(/운영|위탁|청소|정산|리뷰|점유/.test(q))return{stage:'OPERATE',service:'host',page:'host.html',label:'호스트헬퍼',action:'숙소 운영 진단과 위탁/운영 워크스페이스를 시작하세요.'};if(/숙소|예약|여행|행사|단체|외국인/.test(q))return{stage:'FILL',service:'life',page:'life.html',label:'라이프헬퍼',action:'목적과 일정에 맞는 숙박 요청을 등록하세요.'};if(/파트너|협업|투자|매칭|사업가/.test(q))return{stage:'CONNECT',service:'next',page:'next.html',label:'넥스트헬퍼',action:'WANT/OFFER를 등록하고 첫 비즈니스 매칭을 시작하세요.'};return{stage:'FIND',service:'gongsil',page:'gongsil.html',label:'공실헬퍼',action:'먼저 현재 사업 공간과 조건을 탐색해보세요.'}};
async function diagnosis(){const input=document.querySelector('[data-hu-diagnosis-input]');const r=recommend(input?.value||'');if(window.HU.user)await window.HU.setJourney(r.stage,r.service,r.action);window.HU.openInfo(`<small>HELPER ROUTER</small><h2>${esc(r.label)}를 추천합니다.</h2><p>${esc(r.action)}</p><div class="huActionRow"><button class="primary" data-live-href="${r.page}">추천 서비스로 이동</button><button data-hu-myroles>내 Helper ID 확인</button></div>`)}
function bindUniverse(){if(window.HU.cfg.service!=='universe')return;document.querySelectorAll('[data-hu-diagnosis]').forEach(b=>b.addEventListener('click',diagnosis));document.querySelector('[data-hu-diagnosis-input]')?.addEventListener('keydown',e=>{if(e.key==='Enter')diagnosis()})}
async function supplierWorkspace(){if(window.HU.cfg.service!=='life'||!window.HU.user)return;document.querySelector('[data-life-supplier-open]')?.remove();document.querySelector('#supplier')?.remove();if(!(window.HU.hasRole('supplier')||window.HU.isOperator()))return;const nav=document.querySelector('.top nav');if(nav){const b=document.createElement('button');b.className='ghost';b.type='button';b.textContent='공급자';b.dataset.lifeSupplierOpen='';nav.appendChild(b)}const sec=document.createElement('section');sec.id='supplier';sec.className='screen';sec.innerHTML=`<div class="shell"><aside class="side"><button class="active">공급자 대시보드</button><button>서비스 등록</button><button>기업·단체 견적</button><button>예약/정산</button><button>메시지</button></aside><main class="main"><div class="pageTitle"><div><h1>공급자 워크스페이스</h1><p>숙박 외 체험·투어·청소·리넨·이동 등 검증된 서비스를 등록하고 단체 수요와 연결합니다.</p></div></div><div data-supplier-live></div></main></div>`;document.querySelector('.app')?.appendChild(sec);await renderSupplier()}
async function renderSupplier(){const root=document.querySelector('[data-supplier-live]');if(!root)return;const {data,error}=await window.HU.sb.from('hu_life_supplier_services').select('*').eq('owner_id',window.HU.user.id).order('created_at',{ascending:false});if(error)return window.HU.fail(error);root.innerHTML=`<section class="huLive"><div class="huLiveHead"><h2>내 공급 서비스</h2><span>${data?.length||0}개</span></div>${(data||[]).map(s=>`<div class="huRoleReq"><div><b>${esc(s.title)}</b><p>${esc(s.category)} · ${esc(s.region||'지역 미설정')} · ${Number(s.unit_price||0).toLocaleString('ko-KR')}원</p></div><span class="huStatus">${esc(s.status)}</span></div>`).join('')||'<div class="huEmpty">등록된 공급 서비스가 없습니다.</div>'}<details style="margin-top:14px"><summary style="font-weight:800;cursor:pointer">+ 공급 서비스 등록</summary><form class="huForm" data-supplier-form style="margin-top:12px"><label>카테고리<select name="category"><option>체험/투어</option><option>청소/리넨</option><option>이동/차량</option><option>행사/통역</option><option>기타</option></select></label><label>서비스명<input name="title" required></label><label>지역<input name="region" placeholder="서울/수도권/전국"></label><label>단가<input name="price" type="number" min="0" value="0"></label><label>설명<textarea name="description" maxlength="1000"></textarea></label><button>검토용 서비스 등록</button></form></details></section>`}
document.addEventListener('click',e=>{const b=e.target.closest('[data-life-supplier-open]');if(!b)return;window.HU.setScreen('supplier')});document.addEventListener('submit',async e=>{const f=e.target.closest('[data-supplier-form]');if(!f)return;e.preventDefault();const fd=new FormData(f);const {error}=await window.HU.sb.from('hu_life_supplier_services').insert({owner_id:window.HU.user.id,category:String(fd.get('category')),title:String(fd.get('title')),region:String(fd.get('region')||''),unit_price:Number(fd.get('price')||0),description:String(fd.get('description')||''),status:'reviewing'});if(error)return window.HU.fail(error);window.HU.toast('공급 서비스를 검토 요청으로 등록했습니다.');f.reset();await renderSupplier()});
wait().then(()=>{bindUniverse();supplierWorkspace()});document.addEventListener('hu:auth',()=>{bindUniverse();supplierWorkspace()});
})();